let endPoint = {
  Login: "api-user-login",
  SignUp: "api-user-registation",
  dashboard: "api-get-dashboard-data",
  fundHistory: "api-fund-request-history",
  passwordChange: "api-change-password",
  bankDetails: "api-add-user-bank-details",
  wallet_amount: "api-user-wallet-balance",
  bid_history: "api-bid-history-data",
  win_history: "api-wining-history-data",
  userprofile: "api-get-profile",
  walletStatement: "api-get-statement",
  notifications: "api-get-notification",
  gameRates: "api-game-rates",
  SubmitBid: "api-submit-bid",
  galiGames: "api-galidisswar-game",
  indexPageGames: "api-index-game-name-results",
  galiDesawarBid: "api-galidisswar-submit-bid",
  galidisswarBidHistory: "api-galidisswar-bid-history-data",
  galidisswarWiningHistory: "api-galidisswar-wining-history-data",
  userUpiDetails: "api-add-user-upi-details",
  userBankDetails: "api-add-user-bank-details",
  galidisswarGameRates: "api-galidisswar-game-rates",
  userPaymentDetails: "api-get-user-payment-details",
  withdrawTransactionHistory: "api-user-withdraw-transaction-history",
  userWithdrawFundRequest: "api-user-withdraw-fund-request",
  addFundRequest: "api-fund-request-add",
  howToPlay: "api-how-to-play",
  homePageSlider: "api-get-slider-images",
  allblogs: "api-list-all-blogs",
  blogDetails: "api-get-blog-details-by-url/",
  gamePageDetails: "get-article?slug=",
  contactDetails: "contact-settings-grid-data",
  ApiCheckMobile: "api-check-mobile",
  sendotp: "api-otp-sent",
  VerifyOTP: "api-otp-verify",
  ForgotOTP: "api-otp-forgot-verify",
  ForgotPassword: "api-forgot-password",
  WalletHistoryAPI: "api-wallet-transaction-history",
  GetNewsLine: "api-get-news-line",
  InitiateRazorPayApi: "api-get-initiate-rzp",
};

export default endPoint;
